apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-contraint
spec:
  limits:
    - default:
        cpu: 500m
      defaultRequest:
        cpu: 500m
      max:
        cpu: "1"
      min:
        cpu: 100m
      type: Container