apiVersion: v1
kind: ResourceOuota
metadata:
  name: compute-quota
  namespace: dev

spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.mempry: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi